apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/taneem/foobar-operator-index:latest
  displayName: Custom Catalog
  updateStrategy:
    registryPoll: 
      interval: 5m
